export const nycData = [
  {
    category: "london",
    address: "12 Baker Street",
    houseInfo: "Sherlock Holmes Museum - London NW1 6XE",
    room: 2,
    bed: 3,
    bath: 1,
    area: 650,
    image_link:
      "https://images.unsplash.com/photo-1566515610329-94f02c3707d6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bG9uZG9uJTIwaG91c2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    rent: 3300,
    label: true,
  },
  {
    category: "london",
    address: "10 Downing Street",
    houseInfo: "The official residence of the Prime Minister ",
    room: 5,
    bed: 6,
    bath: 3,
    area: 1200,
    image_link:
      "https://www.shutterstock.com/shutterstock/photos/149077361/display_1500/stock-photo-london-street-of-typical-small-th-century-victorian-terraced-houses-without-parked-cars-149077361.jpg",
    rent: 1800,
    label: false,
  },
  {
    category: "london",
    address: "4 Privet Drive",
    houseInfo: "home of Harry Potter's relatives, the Dursleys",
    room: 3,
    bed: 4,
    bath: 2,
    area: 800,
    image_link:
      "https://hips.hearstapps.com/hmg-prod/images/skinny-house-chelsea-london-for-sale-1663240457.jpeg",
    rent: 2000,
  },
  {
    category: "london",
    address: "221A Baker Street",
    houseInfo: " Dr. John Watson, Sherlock Holmes' friend and assistant",
    room: 2,
    bed: 2,
    bath: 1,
    area: 600,
    image_link:
      "https://tpfg3.imgix.net/_1200x630_crop_center-center_82_none/1552644731_house_in_London_with_gardens.jpg?mtime=1637940280",
    rent: 1200,
  },
  {
    category: "london",
    address: "23 Brook Street",
    houseInfo: "home of Jimi Hendrix, the rock guitarist",
    room: 1,
    bed: 1,
    bath: 1,
    area: 400,
    image_link:
      "https://media.rightmove.co.uk/dir/70k/69298/137569316/69298_26541135_IMG_20_0000_max_476x317.jpeg",
    rent: 1500,
    label: true,
  },
  {
    category: "london",
    address: "23 sapphire Street",
    houseInfo: "Oak shelters, the rock guitarist",
    room: 1,
    bed: 4,
    bath: 1,
    area: 540,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDfCcUTFSDf_znBBIFKopy4VYpD-xJlSSX9A&usqp=CAU",
    rent: 1540,
  },
  {
    category: "london",
    address: "221A junior Street",
    houseInfo: " Dr. Megan Holmes' friend and assistant",
    room: 2,
    bed: 2,
    bath: 1,
    area: 600,
    image_link:
      "https://cdn.homedit.com/wp-content/uploads/2009/08/luxury-london-property-by-harrison-varma.jpg",
    rent: 3300,
    label: true,
  },
  {
    category: "london",
    address: "23 sanders Street",
    houseInfo: "home of Gibson jordans, the rock guitarist",
    room: 1,
    bed: 1,
    bath: 1,
    area: 400,
    image_link:
      "https://marriottconstruction.co.uk/assets/images/1-hertfordshire-new-build-mansion.jpg",
    rent: 2200,
  },
  {
    category: "london",
    address: "23 sapphire Street",
    houseInfo: "Oak Tree adobe, the rock guitarist",
    room: 1,
    bed: 4,
    bath: 1,
    area: 540,
    image_link:
      "https://media.architecturaldigest.com/photos/61322b96cf69d71d4a0d38a7/16:9/w_2560%2Cc_limit/OWO%2520apartment%2520terrace.jpeg",
    rent: 7740,
  },
];

export const mumbaiData = [
  {
    address: "12 Marine Drive",
    houseInfo: "Sea-facing penthouse, owned by a Bollywood star",
    room: 3,
    bed: 6,
    bath: 4,
    area: 1200,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU110e0lWdtLjWM6-Fa1-itQowM-kFcbgzATdaOGmLUbkFIBsKjiiW18Cdm8RZDJmLwF8&usqp=CAU",
    rent: 5000,
    label: true,
  },
  {
    address: "7 Altamount Road",
    houseInfo: "Spacious villa, near the Antilia skyscraper",
    room: 4,
    bed: 8,
    bath: 5,
    area: 1500,
    image_link:
      "https://im.whatshot.in/img/2018/May/villa-la-palma-1527680554.jpg",
    rent: 6000,
  },
  {
    address: "9 Carter Road",
    houseInfo: "Modern apartment, with a view of the Arabian Sea",
    room: 2,
    bed: 4,
    bath: 3,
    area: 800,
    image_link:
      "https://assets.traveltriangle.com/blog/wp-content/uploads/2020/01/The-Yellow-House-Manori_14th-jan.jpg",
    rent: 3000,
  },
  {
    address: "5 Malabar Hill",
    houseInfo: "Elegant bungalow, surrounded by lush greenery",
    room: 3,
    bed: 5,
    bath: 4,
    area: 1000,
    image_link:
      "https://static.toiimg.com/thumb/msid-88643550,width-400,resizemode-4/88643550.jpg",
    rent: 4000,
  },
  {
    address: "3 Worli Sea Face",
    houseInfo: "Luxury condo, with a private pool and gym",
    room: 2,
    bed: 4,
    bath: 3,
    area: 900,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTCorKnYEU0mbs0feOqQzhIff1YVBKuLjIIh_dzUb1wmSzMptuRG3Yi0-r4GwihyaeCoM&usqp=CAU",
    rent: 3500,
  },
  {
    address: "11 Bandra Kurla Complex",
    houseInfo: "Sleek loft, with a rooftop terrace and a jacuzzi",
    room: 2,
    bed: 4,
    bath: 3,
    area: 850,
    image_link:
      "https://static.toiimg.com/thumb/msid-88643550,width-400,resizemode-4/88643550.jpg",
    rent: 3200,
    label: true,
  },
  {
    address: "6 Juhu Beach",
    houseInfo: "Beachfront cottage, with a private garden and a hammock",
    room: 2,
    bed: 3,
    bath: 2,
    area: 800,
    image_link:
      "https://assets.gqindia.com/photos/5f54835ade5e2aaea53dd8cc/master/w_1600%2Cc_limit/Aashiyana.jpg",
    rent: 2800,
  },
  {
    address: "4 Hiranandani Gardens",
    houseInfo: "Cozy duplex, with a fireplace and a balcony",
    room: 2,
    bed: 3,
    bath: 2,
    area: 750,
    image_link:
      "https://media-cdn.tripadvisor.com/media/vr-splice-j/07/87/58/aa.jpg",
    rent: 2800,
  },
  {
    address: "8 Nariman Point",
    houseInfo: "Stylish studio, with a panoramic view of the city skyline",
    room: 1,
    bed: 2,
    bath: 1,
    area: 600,
    image_link:
      "https://clickstay.s3-eu-west-1.amazonaws.com/images/property/182757/896x597/65231572-beach-apartment-Ovacik-Turkey.jpg",
    rent: 2500,
  },
];

export const parisData = [
  {
    address: "15 Avenue Montaigne",
    houseInfo: "Chic penthouse, with a view of the Eiffel Tower",
    room: 3,
    bed: 6,
    bath: 4,
    area: 1200,
    image_link:
      "https://i0.wp.com/inspirelle.com/wp-content/uploads/2016/11/ParisApartment-AlexisDuclos.jpg?fit=640%2C426&ssl=1",
    rent: 6000,
    label: true,
  },
  {
    address: "8 Rue du Faubourg Saint-Honoré",
    houseInfo: "Elegant mansion, near the Élysée Palace",
    room: 4,
    bed: 8,
    bath: 5,
    area: 1500,
    image_link:
      "https://www.parisattitude.com/Images/Templates/350x200/salon-hotels.jpg",
    rent: 8000,
  },
  {
    address: "12 Boulevard Saint-Germain",
    houseInfo: "Modern loft, with a rooftop terrace and a jacuzzi",
    room: 2,
    bed: 4,
    bath: 3,
    area: 800,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkb-ZwtbOKe6wX7aThMdfLQf0UWSSAOMPMPw&usqp=CAU",
    rent: 4000,
  },
  {
    address: "6 Place des Vosges",
    houseInfo: "Historic apartment, with a fireplace and a balcony",
    room: 2,
    bed: 3,
    bath: 2,
    area: 800,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiPso9sE_-p4g5F8kHp5kK3XbYaTysw1Q2qA&usqp=CAU",
    rent: 3500,
  },
  {
    address: "10 Rue de Rivoli",
    houseInfo: "Cozy studio, with a view of the Louvre Museum",
    room: 1,
    bed: 2,
    bath: 1,
    area: 600,
    image_link:
      "https://theluxurytravelbook.com/storage/media/images/general/og_large/France-Paris-luxury-villa-rent-rue-windsor-residence%20(23)-863c5e.jpg",
    rent: 3000,
    label: true,
  },
  {
    address: "14 Rue de la Paix",
    houseInfo: "Luxury condo, with a private pool and a gym",
    room: 2,
    bed: 4,
    bath: 3,
    area: 900,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdtP7rypI99kTMVnxQKmIjOguUairMwXDhF2o07zGYlS3Rk-Kg4TG4uoRTLSvf5xZFI3Y&usqp=CAU",
    rent: 4500,
  },
  {
    address: "9 Avenue Foch",
    houseInfo: "Stylish penthouse, with a panoramic view of the city skyline",
    room: 3,
    bed: 5,
    bath: 4,
    area: 1100,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMwTjaPm6-UmltxbXmUUWZ7_MIkcCf8iriSw&usqp=CAU",
    rent: 5500,
    label: true,
  },
  {
    address: "5 Rue du Bac",
    houseInfo: "Cozy duplex, with a fireplace and a balcony",
    room: 2,
    bed: 3,
    bath: 2,
    area: 750,
    image_link:
      "https://qph.cf2.quoracdn.net/main-qimg-65c95bd599f7621880f8055112959aca-lq",
    rent: 3200,
  },
];

export const londonData = [
  {
    address: "10 Kensington Palace Gardens",
    houseInfo: "Royal mansion, near the residence of the Duke ",
    room: 5,
    bed: 10,
    bath: 6,
    area: 2000,
    image_link: "https://www.housesforsaleinwales.co.uk/images/banner1.jpg",
    rent: 10000,
  },
  {
    address: "8 Eaton Square",
    houseInfo: "Elegant townhouse, with a sweet spa ",
    room: 4,
    bed: 8,
    bath: 5,
    area: 1500,
    image_link:
      "https://images.squarespace-cdn.com/content/v1/53250238e4b0dea732e98281/1397906649322-O9N30VD0ZAWD6A6MGA56/002.jpg",
    rent: 8000,
  },
  {
    address: "12 The Bishops Avenue",
    houseInfo: "Luxury villa, with a private pool and a gym",
    room: 3,
    bed: 6,
    bath: 4,
    area: 1200,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR334q3yM-4y6GuB7lly4pEQzWcP3WWtAFbow&usqp=CAU",
    rent: 6000,
    label: true,
  },
  {
    address: "9 Hyde Park Gardens",
    houseInfo: "Spacious penthouse, with a rooftop terrace and a jacuzzi",
    room: 2,
    bed: 4,
    bath: 3,
    area: 900,
    image_link:
      "https://i2-prod.walesonline.co.uk/incoming/article1991188.ece/ALTERNATES/s615/plas-home-657608579.jpg",
    rent: 5000,
  },
  {
    address: "7 Mayfair Place",
    houseInfo: "Stylish apartment, with balcony",
    room: 2,
    bed: 3,
    bath: 2,
    area: 800,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRATFKEU9IZShk0S8HqQSgNMDzS-laN3g8Ypw&usqp=CAU",
    rent: 4000,
  },
  {
    address: "6 Chelsea Square",
    houseInfo: "Charming townhouse, with a garden ",
    room: 2,
    bed: 3,
    bath: 2,
    area: 800,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiSxIANqfZp6iWLusciICUDy1ZdNqwSutrXA&usqp=CAU",
    rent: 3500,
    label: true,
  },
  {
    address: "11 Covent Garden",
    houseInfo: "Cozy studio, the Royal Opera House",
    room: 1,
    bed: 2,
    bath: 1,
    area: 600,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0hhQALDPWaw7Sc29PwDwVhnBQK0zRsY-aUw&usqp=CAU",
    rent: 3000,
  },
  {
    address: "14 Piccadilly Circus",
    houseInfo: "Modern loft, with a  view of skyline",
    room: 2,
    bed: 4,
    bath: 3,
    area: 850,
    image_link:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEvLIj11ik7vPZIg2agq81q9MvRlqExEq1Ug&usqp=CAU",
    rent: 4500,
    label: true,
  },
];
